=begin
#lockally control plane

#The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 

The version of the OpenAPI document: 0.1.0
Contact: support@lockally.com
Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module Lockally
  class BillingStatus < ApiModelBase
    attr_accessor :plan

    attr_accessor :display_name

    attr_accessor :mode

    attr_accessor :rate_cap_per_min

    attr_accessor :monthly_included_sends

    attr_accessor :msgs_this_period

    attr_accessor :status

    attr_accessor :price_naira_per_seat

    attr_accessor :subscribed_at

    attr_accessor :current_period_end

    attr_accessor :created_at

    attr_accessor :send_units_balance

    attr_accessor :send_units_next_expiry

    attr_accessor :unit_bundles

    attr_accessor :catalog

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'plan' => :'plan',
        :'display_name' => :'display_name',
        :'mode' => :'mode',
        :'rate_cap_per_min' => :'rate_cap_per_min',
        :'monthly_included_sends' => :'monthly_included_sends',
        :'msgs_this_period' => :'msgs_this_period',
        :'status' => :'status',
        :'price_naira_per_seat' => :'price_naira_per_seat',
        :'subscribed_at' => :'subscribed_at',
        :'current_period_end' => :'current_period_end',
        :'created_at' => :'created_at',
        :'send_units_balance' => :'send_units_balance',
        :'send_units_next_expiry' => :'send_units_next_expiry',
        :'unit_bundles' => :'unit_bundles',
        :'catalog' => :'catalog'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'plan' => :'String',
        :'display_name' => :'String',
        :'mode' => :'String',
        :'rate_cap_per_min' => :'Integer',
        :'monthly_included_sends' => :'Integer',
        :'msgs_this_period' => :'Integer',
        :'status' => :'String',
        :'price_naira_per_seat' => :'Integer',
        :'subscribed_at' => :'Time',
        :'current_period_end' => :'Time',
        :'created_at' => :'Time',
        :'send_units_balance' => :'Integer',
        :'send_units_next_expiry' => :'Time',
        :'unit_bundles' => :'Array<UnitBundle>',
        :'catalog' => :'Array<PlanCatalogEntry>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Lockally::BillingStatus` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Lockally::BillingStatus`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'plan')
        self.plan = attributes[:'plan']
      else
        self.plan = nil
      end

      if attributes.key?(:'display_name')
        self.display_name = attributes[:'display_name']
      else
        self.display_name = nil
      end

      if attributes.key?(:'mode')
        self.mode = attributes[:'mode']
      else
        self.mode = nil
      end

      if attributes.key?(:'rate_cap_per_min')
        self.rate_cap_per_min = attributes[:'rate_cap_per_min']
      else
        self.rate_cap_per_min = nil
      end

      if attributes.key?(:'monthly_included_sends')
        self.monthly_included_sends = attributes[:'monthly_included_sends']
      else
        self.monthly_included_sends = nil
      end

      if attributes.key?(:'msgs_this_period')
        self.msgs_this_period = attributes[:'msgs_this_period']
      else
        self.msgs_this_period = nil
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      else
        self.status = nil
      end

      if attributes.key?(:'price_naira_per_seat')
        self.price_naira_per_seat = attributes[:'price_naira_per_seat']
      else
        self.price_naira_per_seat = nil
      end

      if attributes.key?(:'subscribed_at')
        self.subscribed_at = attributes[:'subscribed_at']
      end

      if attributes.key?(:'current_period_end')
        self.current_period_end = attributes[:'current_period_end']
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      else
        self.created_at = nil
      end

      if attributes.key?(:'send_units_balance')
        self.send_units_balance = attributes[:'send_units_balance']
      else
        self.send_units_balance = nil
      end

      if attributes.key?(:'send_units_next_expiry')
        self.send_units_next_expiry = attributes[:'send_units_next_expiry']
      end

      if attributes.key?(:'unit_bundles')
        if (value = attributes[:'unit_bundles']).is_a?(Array)
          self.unit_bundles = value
        end
      else
        self.unit_bundles = nil
      end

      if attributes.key?(:'catalog')
        if (value = attributes[:'catalog']).is_a?(Array)
          self.catalog = value
        end
      else
        self.catalog = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @plan.nil?
        invalid_properties.push('invalid value for "plan", plan cannot be nil.')
      end

      if @display_name.nil?
        invalid_properties.push('invalid value for "display_name", display_name cannot be nil.')
      end

      if @mode.nil?
        invalid_properties.push('invalid value for "mode", mode cannot be nil.')
      end

      if @rate_cap_per_min.nil?
        invalid_properties.push('invalid value for "rate_cap_per_min", rate_cap_per_min cannot be nil.')
      end

      if @monthly_included_sends.nil?
        invalid_properties.push('invalid value for "monthly_included_sends", monthly_included_sends cannot be nil.')
      end

      if @msgs_this_period.nil?
        invalid_properties.push('invalid value for "msgs_this_period", msgs_this_period cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      if @price_naira_per_seat.nil?
        invalid_properties.push('invalid value for "price_naira_per_seat", price_naira_per_seat cannot be nil.')
      end

      if @created_at.nil?
        invalid_properties.push('invalid value for "created_at", created_at cannot be nil.')
      end

      if @send_units_balance.nil?
        invalid_properties.push('invalid value for "send_units_balance", send_units_balance cannot be nil.')
      end

      if @unit_bundles.nil?
        invalid_properties.push('invalid value for "unit_bundles", unit_bundles cannot be nil.')
      end

      if @catalog.nil?
        invalid_properties.push('invalid value for "catalog", catalog cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @plan.nil?
      return false if @display_name.nil?
      return false if @mode.nil?
      mode_validator = EnumAttributeValidator.new('String', ["api", "business", "both"])
      return false unless mode_validator.valid?(@mode)
      return false if @rate_cap_per_min.nil?
      return false if @monthly_included_sends.nil?
      return false if @msgs_this_period.nil?
      return false if @status.nil?
      status_validator = EnumAttributeValidator.new('String', ["active", "suspended"])
      return false unless status_validator.valid?(@status)
      return false if @price_naira_per_seat.nil?
      return false if @created_at.nil?
      return false if @send_units_balance.nil?
      return false if @unit_bundles.nil?
      return false if @catalog.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] plan Value to be assigned
    def plan=(plan)
      if plan.nil?
        fail ArgumentError, 'plan cannot be nil'
      end

      @plan = plan
    end

    # Custom attribute writer method with validation
    # @param [Object] display_name Value to be assigned
    def display_name=(display_name)
      if display_name.nil?
        fail ArgumentError, 'display_name cannot be nil'
      end

      @display_name = display_name
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] mode Object to be assigned
    def mode=(mode)
      validator = EnumAttributeValidator.new('String', ["api", "business", "both"])
      unless validator.valid?(mode)
        fail ArgumentError, "invalid value for \"mode\", must be one of #{validator.allowable_values}."
      end
      @mode = mode
    end

    # Custom attribute writer method with validation
    # @param [Object] rate_cap_per_min Value to be assigned
    def rate_cap_per_min=(rate_cap_per_min)
      if rate_cap_per_min.nil?
        fail ArgumentError, 'rate_cap_per_min cannot be nil'
      end

      @rate_cap_per_min = rate_cap_per_min
    end

    # Custom attribute writer method with validation
    # @param [Object] monthly_included_sends Value to be assigned
    def monthly_included_sends=(monthly_included_sends)
      if monthly_included_sends.nil?
        fail ArgumentError, 'monthly_included_sends cannot be nil'
      end

      @monthly_included_sends = monthly_included_sends
    end

    # Custom attribute writer method with validation
    # @param [Object] msgs_this_period Value to be assigned
    def msgs_this_period=(msgs_this_period)
      if msgs_this_period.nil?
        fail ArgumentError, 'msgs_this_period cannot be nil'
      end

      @msgs_this_period = msgs_this_period
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] status Object to be assigned
    def status=(status)
      validator = EnumAttributeValidator.new('String', ["active", "suspended"])
      unless validator.valid?(status)
        fail ArgumentError, "invalid value for \"status\", must be one of #{validator.allowable_values}."
      end
      @status = status
    end

    # Custom attribute writer method with validation
    # @param [Object] price_naira_per_seat Value to be assigned
    def price_naira_per_seat=(price_naira_per_seat)
      if price_naira_per_seat.nil?
        fail ArgumentError, 'price_naira_per_seat cannot be nil'
      end

      @price_naira_per_seat = price_naira_per_seat
    end

    # Custom attribute writer method with validation
    # @param [Object] created_at Value to be assigned
    def created_at=(created_at)
      if created_at.nil?
        fail ArgumentError, 'created_at cannot be nil'
      end

      @created_at = created_at
    end

    # Custom attribute writer method with validation
    # @param [Object] send_units_balance Value to be assigned
    def send_units_balance=(send_units_balance)
      if send_units_balance.nil?
        fail ArgumentError, 'send_units_balance cannot be nil'
      end

      @send_units_balance = send_units_balance
    end

    # Custom attribute writer method with validation
    # @param [Object] unit_bundles Value to be assigned
    def unit_bundles=(unit_bundles)
      if unit_bundles.nil?
        fail ArgumentError, 'unit_bundles cannot be nil'
      end

      @unit_bundles = unit_bundles
    end

    # Custom attribute writer method with validation
    # @param [Object] catalog Value to be assigned
    def catalog=(catalog)
      if catalog.nil?
        fail ArgumentError, 'catalog cannot be nil'
      end

      @catalog = catalog
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          plan == o.plan &&
          display_name == o.display_name &&
          mode == o.mode &&
          rate_cap_per_min == o.rate_cap_per_min &&
          monthly_included_sends == o.monthly_included_sends &&
          msgs_this_period == o.msgs_this_period &&
          status == o.status &&
          price_naira_per_seat == o.price_naira_per_seat &&
          subscribed_at == o.subscribed_at &&
          current_period_end == o.current_period_end &&
          created_at == o.created_at &&
          send_units_balance == o.send_units_balance &&
          send_units_next_expiry == o.send_units_next_expiry &&
          unit_bundles == o.unit_bundles &&
          catalog == o.catalog
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [plan, display_name, mode, rate_cap_per_min, monthly_included_sends, msgs_this_period, status, price_naira_per_seat, subscribed_at, current_period_end, created_at, send_units_balance, send_units_next_expiry, unit_bundles, catalog].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
