=begin
#lockally control plane

#The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 

The version of the OpenAPI document: 0.1.0
Contact: support@lockally.com
Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module Lockally
  class CalendarPolicies < ApiModelBase
    attr_accessor :tenant_id

    attr_accessor :max_meeting_duration_mins

    attr_accessor :working_hours_start

    attr_accessor :working_hours_end

    attr_accessor :booking_window_days

    attr_accessor :recurring_meeting_limit

    attr_accessor :resource_approval_mode

    attr_accessor :external_invites_allowed

    attr_accessor :external_sharing_allowed

    attr_accessor :public_links_enabled

    attr_accessor :created_at

    attr_accessor :updated_at

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'tenant_id' => :'tenant_id',
        :'max_meeting_duration_mins' => :'max_meeting_duration_mins',
        :'working_hours_start' => :'working_hours_start',
        :'working_hours_end' => :'working_hours_end',
        :'booking_window_days' => :'booking_window_days',
        :'recurring_meeting_limit' => :'recurring_meeting_limit',
        :'resource_approval_mode' => :'resource_approval_mode',
        :'external_invites_allowed' => :'external_invites_allowed',
        :'external_sharing_allowed' => :'external_sharing_allowed',
        :'public_links_enabled' => :'public_links_enabled',
        :'created_at' => :'created_at',
        :'updated_at' => :'updated_at'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'tenant_id' => :'String',
        :'max_meeting_duration_mins' => :'Integer',
        :'working_hours_start' => :'String',
        :'working_hours_end' => :'String',
        :'booking_window_days' => :'Integer',
        :'recurring_meeting_limit' => :'Integer',
        :'resource_approval_mode' => :'String',
        :'external_invites_allowed' => :'Boolean',
        :'external_sharing_allowed' => :'Boolean',
        :'public_links_enabled' => :'Boolean',
        :'created_at' => :'Time',
        :'updated_at' => :'Time'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Lockally::CalendarPolicies` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Lockally::CalendarPolicies`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'tenant_id')
        self.tenant_id = attributes[:'tenant_id']
      else
        self.tenant_id = nil
      end

      if attributes.key?(:'max_meeting_duration_mins')
        self.max_meeting_duration_mins = attributes[:'max_meeting_duration_mins']
      end

      if attributes.key?(:'working_hours_start')
        self.working_hours_start = attributes[:'working_hours_start']
      end

      if attributes.key?(:'working_hours_end')
        self.working_hours_end = attributes[:'working_hours_end']
      end

      if attributes.key?(:'booking_window_days')
        self.booking_window_days = attributes[:'booking_window_days']
      end

      if attributes.key?(:'recurring_meeting_limit')
        self.recurring_meeting_limit = attributes[:'recurring_meeting_limit']
      end

      if attributes.key?(:'resource_approval_mode')
        self.resource_approval_mode = attributes[:'resource_approval_mode']
      end

      if attributes.key?(:'external_invites_allowed')
        self.external_invites_allowed = attributes[:'external_invites_allowed']
      end

      if attributes.key?(:'external_sharing_allowed')
        self.external_sharing_allowed = attributes[:'external_sharing_allowed']
      end

      if attributes.key?(:'public_links_enabled')
        self.public_links_enabled = attributes[:'public_links_enabled']
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @tenant_id.nil?
        invalid_properties.push('invalid value for "tenant_id", tenant_id cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @tenant_id.nil?
      resource_approval_mode_validator = EnumAttributeValidator.new('String', ["auto_approve", "require_approval", "restricted"])
      return false unless resource_approval_mode_validator.valid?(@resource_approval_mode)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] tenant_id Value to be assigned
    def tenant_id=(tenant_id)
      if tenant_id.nil?
        fail ArgumentError, 'tenant_id cannot be nil'
      end

      @tenant_id = tenant_id
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] resource_approval_mode Object to be assigned
    def resource_approval_mode=(resource_approval_mode)
      validator = EnumAttributeValidator.new('String', ["auto_approve", "require_approval", "restricted"])
      unless validator.valid?(resource_approval_mode)
        fail ArgumentError, "invalid value for \"resource_approval_mode\", must be one of #{validator.allowable_values}."
      end
      @resource_approval_mode = resource_approval_mode
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          tenant_id == o.tenant_id &&
          max_meeting_duration_mins == o.max_meeting_duration_mins &&
          working_hours_start == o.working_hours_start &&
          working_hours_end == o.working_hours_end &&
          booking_window_days == o.booking_window_days &&
          recurring_meeting_limit == o.recurring_meeting_limit &&
          resource_approval_mode == o.resource_approval_mode &&
          external_invites_allowed == o.external_invites_allowed &&
          external_sharing_allowed == o.external_sharing_allowed &&
          public_links_enabled == o.public_links_enabled &&
          created_at == o.created_at &&
          updated_at == o.updated_at
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [tenant_id, max_meeting_duration_mins, working_hours_start, working_hours_end, booking_window_days, recurring_meeting_limit, resource_approval_mode, external_invites_allowed, external_sharing_allowed, public_links_enabled, created_at, updated_at].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
