=begin
#lockally control plane

#The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 

The version of the OpenAPI document: 0.1.0
Contact: support@lockally.com
Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module Lockally
  class GALSettings < ApiModelBase
    attr_accessor :tenant_id

    attr_accessor :gal_enabled

    attr_accessor :hide_from_directory

    attr_accessor :department_grouping

    attr_accessor :search_visibility

    attr_accessor :include_external_contacts

    attr_accessor :last_index_rebuilt_at

    attr_accessor :last_synced_at

    attr_accessor :created_at

    attr_accessor :updated_at

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'tenant_id' => :'tenant_id',
        :'gal_enabled' => :'gal_enabled',
        :'hide_from_directory' => :'hide_from_directory',
        :'department_grouping' => :'department_grouping',
        :'search_visibility' => :'search_visibility',
        :'include_external_contacts' => :'include_external_contacts',
        :'last_index_rebuilt_at' => :'last_index_rebuilt_at',
        :'last_synced_at' => :'last_synced_at',
        :'created_at' => :'created_at',
        :'updated_at' => :'updated_at'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'tenant_id' => :'String',
        :'gal_enabled' => :'Boolean',
        :'hide_from_directory' => :'Boolean',
        :'department_grouping' => :'Boolean',
        :'search_visibility' => :'String',
        :'include_external_contacts' => :'Boolean',
        :'last_index_rebuilt_at' => :'Time',
        :'last_synced_at' => :'Time',
        :'created_at' => :'Time',
        :'updated_at' => :'Time'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Lockally::GALSettings` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Lockally::GALSettings`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'tenant_id')
        self.tenant_id = attributes[:'tenant_id']
      else
        self.tenant_id = nil
      end

      if attributes.key?(:'gal_enabled')
        self.gal_enabled = attributes[:'gal_enabled']
      else
        self.gal_enabled = nil
      end

      if attributes.key?(:'hide_from_directory')
        self.hide_from_directory = attributes[:'hide_from_directory']
      else
        self.hide_from_directory = nil
      end

      if attributes.key?(:'department_grouping')
        self.department_grouping = attributes[:'department_grouping']
      else
        self.department_grouping = nil
      end

      if attributes.key?(:'search_visibility')
        self.search_visibility = attributes[:'search_visibility']
      else
        self.search_visibility = nil
      end

      if attributes.key?(:'include_external_contacts')
        self.include_external_contacts = attributes[:'include_external_contacts']
      else
        self.include_external_contacts = nil
      end

      if attributes.key?(:'last_index_rebuilt_at')
        self.last_index_rebuilt_at = attributes[:'last_index_rebuilt_at']
      end

      if attributes.key?(:'last_synced_at')
        self.last_synced_at = attributes[:'last_synced_at']
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @tenant_id.nil?
        invalid_properties.push('invalid value for "tenant_id", tenant_id cannot be nil.')
      end

      if @gal_enabled.nil?
        invalid_properties.push('invalid value for "gal_enabled", gal_enabled cannot be nil.')
      end

      if @hide_from_directory.nil?
        invalid_properties.push('invalid value for "hide_from_directory", hide_from_directory cannot be nil.')
      end

      if @department_grouping.nil?
        invalid_properties.push('invalid value for "department_grouping", department_grouping cannot be nil.')
      end

      if @search_visibility.nil?
        invalid_properties.push('invalid value for "search_visibility", search_visibility cannot be nil.')
      end

      if @include_external_contacts.nil?
        invalid_properties.push('invalid value for "include_external_contacts", include_external_contacts cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @tenant_id.nil?
      return false if @gal_enabled.nil?
      return false if @hide_from_directory.nil?
      return false if @department_grouping.nil?
      return false if @search_visibility.nil?
      search_visibility_validator = EnumAttributeValidator.new('String', ["all_users", "same_department", "admins_only"])
      return false unless search_visibility_validator.valid?(@search_visibility)
      return false if @include_external_contacts.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] tenant_id Value to be assigned
    def tenant_id=(tenant_id)
      if tenant_id.nil?
        fail ArgumentError, 'tenant_id cannot be nil'
      end

      @tenant_id = tenant_id
    end

    # Custom attribute writer method with validation
    # @param [Object] gal_enabled Value to be assigned
    def gal_enabled=(gal_enabled)
      if gal_enabled.nil?
        fail ArgumentError, 'gal_enabled cannot be nil'
      end

      @gal_enabled = gal_enabled
    end

    # Custom attribute writer method with validation
    # @param [Object] hide_from_directory Value to be assigned
    def hide_from_directory=(hide_from_directory)
      if hide_from_directory.nil?
        fail ArgumentError, 'hide_from_directory cannot be nil'
      end

      @hide_from_directory = hide_from_directory
    end

    # Custom attribute writer method with validation
    # @param [Object] department_grouping Value to be assigned
    def department_grouping=(department_grouping)
      if department_grouping.nil?
        fail ArgumentError, 'department_grouping cannot be nil'
      end

      @department_grouping = department_grouping
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] search_visibility Object to be assigned
    def search_visibility=(search_visibility)
      validator = EnumAttributeValidator.new('String', ["all_users", "same_department", "admins_only"])
      unless validator.valid?(search_visibility)
        fail ArgumentError, "invalid value for \"search_visibility\", must be one of #{validator.allowable_values}."
      end
      @search_visibility = search_visibility
    end

    # Custom attribute writer method with validation
    # @param [Object] include_external_contacts Value to be assigned
    def include_external_contacts=(include_external_contacts)
      if include_external_contacts.nil?
        fail ArgumentError, 'include_external_contacts cannot be nil'
      end

      @include_external_contacts = include_external_contacts
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          tenant_id == o.tenant_id &&
          gal_enabled == o.gal_enabled &&
          hide_from_directory == o.hide_from_directory &&
          department_grouping == o.department_grouping &&
          search_visibility == o.search_visibility &&
          include_external_contacts == o.include_external_contacts &&
          last_index_rebuilt_at == o.last_index_rebuilt_at &&
          last_synced_at == o.last_synced_at &&
          created_at == o.created_at &&
          updated_at == o.updated_at
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [tenant_id, gal_enabled, hide_from_directory, department_grouping, search_visibility, include_external_contacts, last_index_rebuilt_at, last_synced_at, created_at, updated_at].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
