=begin
#lockally control plane

#The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 

The version of the OpenAPI document: 0.1.0
Contact: support@lockally.com
Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module Lockally
  class Mailbox < ApiModelBase
    attr_accessor :id

    attr_accessor :tenant_id

    attr_accessor :domain_id

    attr_accessor :email

    attr_accessor :quota_bytes

    attr_accessor :disabled

    attr_accessor :disabled_at

    attr_accessor :soft_deleted_at

    attr_accessor :hard_delete_after

    attr_accessor :created_at

    # ONLY present on POST response when lockally generated the password. Shown once.
    attr_accessor :password

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'tenant_id' => :'tenant_id',
        :'domain_id' => :'domain_id',
        :'email' => :'email',
        :'quota_bytes' => :'quota_bytes',
        :'disabled' => :'disabled',
        :'disabled_at' => :'disabled_at',
        :'soft_deleted_at' => :'soft_deleted_at',
        :'hard_delete_after' => :'hard_delete_after',
        :'created_at' => :'created_at',
        :'password' => :'password'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'tenant_id' => :'String',
        :'domain_id' => :'String',
        :'email' => :'String',
        :'quota_bytes' => :'Integer',
        :'disabled' => :'Boolean',
        :'disabled_at' => :'Time',
        :'soft_deleted_at' => :'Time',
        :'hard_delete_after' => :'Time',
        :'created_at' => :'Time',
        :'password' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Lockally::Mailbox` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Lockally::Mailbox`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'tenant_id')
        self.tenant_id = attributes[:'tenant_id']
      else
        self.tenant_id = nil
      end

      if attributes.key?(:'domain_id')
        self.domain_id = attributes[:'domain_id']
      else
        self.domain_id = nil
      end

      if attributes.key?(:'email')
        self.email = attributes[:'email']
      else
        self.email = nil
      end

      if attributes.key?(:'quota_bytes')
        self.quota_bytes = attributes[:'quota_bytes']
      else
        self.quota_bytes = nil
      end

      if attributes.key?(:'disabled')
        self.disabled = attributes[:'disabled']
      else
        self.disabled = nil
      end

      if attributes.key?(:'disabled_at')
        self.disabled_at = attributes[:'disabled_at']
      end

      if attributes.key?(:'soft_deleted_at')
        self.soft_deleted_at = attributes[:'soft_deleted_at']
      end

      if attributes.key?(:'hard_delete_after')
        self.hard_delete_after = attributes[:'hard_delete_after']
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      else
        self.created_at = nil
      end

      if attributes.key?(:'password')
        self.password = attributes[:'password']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @tenant_id.nil?
        invalid_properties.push('invalid value for "tenant_id", tenant_id cannot be nil.')
      end

      if @domain_id.nil?
        invalid_properties.push('invalid value for "domain_id", domain_id cannot be nil.')
      end

      if @email.nil?
        invalid_properties.push('invalid value for "email", email cannot be nil.')
      end

      if @quota_bytes.nil?
        invalid_properties.push('invalid value for "quota_bytes", quota_bytes cannot be nil.')
      end

      if @disabled.nil?
        invalid_properties.push('invalid value for "disabled", disabled cannot be nil.')
      end

      if @created_at.nil?
        invalid_properties.push('invalid value for "created_at", created_at cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @tenant_id.nil?
      return false if @domain_id.nil?
      return false if @email.nil?
      return false if @quota_bytes.nil?
      return false if @disabled.nil?
      return false if @created_at.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] tenant_id Value to be assigned
    def tenant_id=(tenant_id)
      if tenant_id.nil?
        fail ArgumentError, 'tenant_id cannot be nil'
      end

      @tenant_id = tenant_id
    end

    # Custom attribute writer method with validation
    # @param [Object] domain_id Value to be assigned
    def domain_id=(domain_id)
      if domain_id.nil?
        fail ArgumentError, 'domain_id cannot be nil'
      end

      @domain_id = domain_id
    end

    # Custom attribute writer method with validation
    # @param [Object] email Value to be assigned
    def email=(email)
      if email.nil?
        fail ArgumentError, 'email cannot be nil'
      end

      @email = email
    end

    # Custom attribute writer method with validation
    # @param [Object] quota_bytes Value to be assigned
    def quota_bytes=(quota_bytes)
      if quota_bytes.nil?
        fail ArgumentError, 'quota_bytes cannot be nil'
      end

      @quota_bytes = quota_bytes
    end

    # Custom attribute writer method with validation
    # @param [Object] disabled Value to be assigned
    def disabled=(disabled)
      if disabled.nil?
        fail ArgumentError, 'disabled cannot be nil'
      end

      @disabled = disabled
    end

    # Custom attribute writer method with validation
    # @param [Object] created_at Value to be assigned
    def created_at=(created_at)
      if created_at.nil?
        fail ArgumentError, 'created_at cannot be nil'
      end

      @created_at = created_at
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          tenant_id == o.tenant_id &&
          domain_id == o.domain_id &&
          email == o.email &&
          quota_bytes == o.quota_bytes &&
          disabled == o.disabled &&
          disabled_at == o.disabled_at &&
          soft_deleted_at == o.soft_deleted_at &&
          hard_delete_after == o.hard_delete_after &&
          created_at == o.created_at &&
          password == o.password
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, tenant_id, domain_id, email, quota_bytes, disabled, disabled_at, soft_deleted_at, hard_delete_after, created_at, password].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
