=begin
#lockally control plane

#The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 

The version of the OpenAPI document: 0.1.0
Contact: support@lockally.com
Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module Lockally
  class MigrationProgress < ApiModelBase
    attr_accessor :migration_id

    attr_accessor :status

    attr_accessor :total_mailboxes

    attr_accessor :completed_mailboxes

    attr_accessor :failed_mailboxes

    attr_accessor :total_messages

    attr_accessor :synced_messages

    attr_accessor :failed_messages

    attr_accessor :percent_complete

    attr_accessor :mailboxes

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'migration_id' => :'migration_id',
        :'status' => :'status',
        :'total_mailboxes' => :'total_mailboxes',
        :'completed_mailboxes' => :'completed_mailboxes',
        :'failed_mailboxes' => :'failed_mailboxes',
        :'total_messages' => :'total_messages',
        :'synced_messages' => :'synced_messages',
        :'failed_messages' => :'failed_messages',
        :'percent_complete' => :'percent_complete',
        :'mailboxes' => :'mailboxes'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'migration_id' => :'String',
        :'status' => :'String',
        :'total_mailboxes' => :'Integer',
        :'completed_mailboxes' => :'Integer',
        :'failed_mailboxes' => :'Integer',
        :'total_messages' => :'Integer',
        :'synced_messages' => :'Integer',
        :'failed_messages' => :'Integer',
        :'percent_complete' => :'Float',
        :'mailboxes' => :'Array<MigrationProgressMailboxesInner>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Lockally::MigrationProgress` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Lockally::MigrationProgress`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'migration_id')
        self.migration_id = attributes[:'migration_id']
      else
        self.migration_id = nil
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      else
        self.status = nil
      end

      if attributes.key?(:'total_mailboxes')
        self.total_mailboxes = attributes[:'total_mailboxes']
      else
        self.total_mailboxes = nil
      end

      if attributes.key?(:'completed_mailboxes')
        self.completed_mailboxes = attributes[:'completed_mailboxes']
      else
        self.completed_mailboxes = nil
      end

      if attributes.key?(:'failed_mailboxes')
        self.failed_mailboxes = attributes[:'failed_mailboxes']
      else
        self.failed_mailboxes = nil
      end

      if attributes.key?(:'total_messages')
        self.total_messages = attributes[:'total_messages']
      else
        self.total_messages = nil
      end

      if attributes.key?(:'synced_messages')
        self.synced_messages = attributes[:'synced_messages']
      else
        self.synced_messages = nil
      end

      if attributes.key?(:'failed_messages')
        self.failed_messages = attributes[:'failed_messages']
      else
        self.failed_messages = nil
      end

      if attributes.key?(:'percent_complete')
        self.percent_complete = attributes[:'percent_complete']
      else
        self.percent_complete = nil
      end

      if attributes.key?(:'mailboxes')
        if (value = attributes[:'mailboxes']).is_a?(Array)
          self.mailboxes = value
        end
      else
        self.mailboxes = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @migration_id.nil?
        invalid_properties.push('invalid value for "migration_id", migration_id cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      if @total_mailboxes.nil?
        invalid_properties.push('invalid value for "total_mailboxes", total_mailboxes cannot be nil.')
      end

      if @completed_mailboxes.nil?
        invalid_properties.push('invalid value for "completed_mailboxes", completed_mailboxes cannot be nil.')
      end

      if @failed_mailboxes.nil?
        invalid_properties.push('invalid value for "failed_mailboxes", failed_mailboxes cannot be nil.')
      end

      if @total_messages.nil?
        invalid_properties.push('invalid value for "total_messages", total_messages cannot be nil.')
      end

      if @synced_messages.nil?
        invalid_properties.push('invalid value for "synced_messages", synced_messages cannot be nil.')
      end

      if @failed_messages.nil?
        invalid_properties.push('invalid value for "failed_messages", failed_messages cannot be nil.')
      end

      if @percent_complete.nil?
        invalid_properties.push('invalid value for "percent_complete", percent_complete cannot be nil.')
      end

      if @mailboxes.nil?
        invalid_properties.push('invalid value for "mailboxes", mailboxes cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @migration_id.nil?
      return false if @status.nil?
      return false if @total_mailboxes.nil?
      return false if @completed_mailboxes.nil?
      return false if @failed_mailboxes.nil?
      return false if @total_messages.nil?
      return false if @synced_messages.nil?
      return false if @failed_messages.nil?
      return false if @percent_complete.nil?
      return false if @mailboxes.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] migration_id Value to be assigned
    def migration_id=(migration_id)
      if migration_id.nil?
        fail ArgumentError, 'migration_id cannot be nil'
      end

      @migration_id = migration_id
    end

    # Custom attribute writer method with validation
    # @param [Object] status Value to be assigned
    def status=(status)
      if status.nil?
        fail ArgumentError, 'status cannot be nil'
      end

      @status = status
    end

    # Custom attribute writer method with validation
    # @param [Object] total_mailboxes Value to be assigned
    def total_mailboxes=(total_mailboxes)
      if total_mailboxes.nil?
        fail ArgumentError, 'total_mailboxes cannot be nil'
      end

      @total_mailboxes = total_mailboxes
    end

    # Custom attribute writer method with validation
    # @param [Object] completed_mailboxes Value to be assigned
    def completed_mailboxes=(completed_mailboxes)
      if completed_mailboxes.nil?
        fail ArgumentError, 'completed_mailboxes cannot be nil'
      end

      @completed_mailboxes = completed_mailboxes
    end

    # Custom attribute writer method with validation
    # @param [Object] failed_mailboxes Value to be assigned
    def failed_mailboxes=(failed_mailboxes)
      if failed_mailboxes.nil?
        fail ArgumentError, 'failed_mailboxes cannot be nil'
      end

      @failed_mailboxes = failed_mailboxes
    end

    # Custom attribute writer method with validation
    # @param [Object] total_messages Value to be assigned
    def total_messages=(total_messages)
      if total_messages.nil?
        fail ArgumentError, 'total_messages cannot be nil'
      end

      @total_messages = total_messages
    end

    # Custom attribute writer method with validation
    # @param [Object] synced_messages Value to be assigned
    def synced_messages=(synced_messages)
      if synced_messages.nil?
        fail ArgumentError, 'synced_messages cannot be nil'
      end

      @synced_messages = synced_messages
    end

    # Custom attribute writer method with validation
    # @param [Object] failed_messages Value to be assigned
    def failed_messages=(failed_messages)
      if failed_messages.nil?
        fail ArgumentError, 'failed_messages cannot be nil'
      end

      @failed_messages = failed_messages
    end

    # Custom attribute writer method with validation
    # @param [Object] percent_complete Value to be assigned
    def percent_complete=(percent_complete)
      if percent_complete.nil?
        fail ArgumentError, 'percent_complete cannot be nil'
      end

      @percent_complete = percent_complete
    end

    # Custom attribute writer method with validation
    # @param [Object] mailboxes Value to be assigned
    def mailboxes=(mailboxes)
      if mailboxes.nil?
        fail ArgumentError, 'mailboxes cannot be nil'
      end

      @mailboxes = mailboxes
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          migration_id == o.migration_id &&
          status == o.status &&
          total_mailboxes == o.total_mailboxes &&
          completed_mailboxes == o.completed_mailboxes &&
          failed_mailboxes == o.failed_mailboxes &&
          total_messages == o.total_messages &&
          synced_messages == o.synced_messages &&
          failed_messages == o.failed_messages &&
          percent_complete == o.percent_complete &&
          mailboxes == o.mailboxes
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [migration_id, status, total_mailboxes, completed_mailboxes, failed_mailboxes, total_messages, synced_messages, failed_messages, percent_complete, mailboxes].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
