=begin
#lockally control plane

#The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 

The version of the OpenAPI document: 0.1.0
Contact: support@lockally.com
Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module Lockally
  class PlanCatalogEntry < ApiModelBase
    attr_accessor :name

    attr_accessor :display_name

    attr_accessor :description

    attr_accessor :price_naira_per_seat

    attr_accessor :rate_cap_per_min

    attr_accessor :monthly_included_sends

    attr_accessor :has_shared_mailboxes

    attr_accessor :has_send_units

    attr_accessor :has_ai_units

    attr_accessor :has_e2e_encryption

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'name' => :'name',
        :'display_name' => :'display_name',
        :'description' => :'description',
        :'price_naira_per_seat' => :'price_naira_per_seat',
        :'rate_cap_per_min' => :'rate_cap_per_min',
        :'monthly_included_sends' => :'monthly_included_sends',
        :'has_shared_mailboxes' => :'has_shared_mailboxes',
        :'has_send_units' => :'has_send_units',
        :'has_ai_units' => :'has_ai_units',
        :'has_e2e_encryption' => :'has_e2e_encryption'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'name' => :'String',
        :'display_name' => :'String',
        :'description' => :'String',
        :'price_naira_per_seat' => :'Integer',
        :'rate_cap_per_min' => :'Integer',
        :'monthly_included_sends' => :'Integer',
        :'has_shared_mailboxes' => :'Boolean',
        :'has_send_units' => :'Boolean',
        :'has_ai_units' => :'Boolean',
        :'has_e2e_encryption' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Lockally::PlanCatalogEntry` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Lockally::PlanCatalogEntry`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      else
        self.name = nil
      end

      if attributes.key?(:'display_name')
        self.display_name = attributes[:'display_name']
      else
        self.display_name = nil
      end

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      else
        self.description = nil
      end

      if attributes.key?(:'price_naira_per_seat')
        self.price_naira_per_seat = attributes[:'price_naira_per_seat']
      else
        self.price_naira_per_seat = nil
      end

      if attributes.key?(:'rate_cap_per_min')
        self.rate_cap_per_min = attributes[:'rate_cap_per_min']
      else
        self.rate_cap_per_min = nil
      end

      if attributes.key?(:'monthly_included_sends')
        self.monthly_included_sends = attributes[:'monthly_included_sends']
      else
        self.monthly_included_sends = nil
      end

      if attributes.key?(:'has_shared_mailboxes')
        self.has_shared_mailboxes = attributes[:'has_shared_mailboxes']
      else
        self.has_shared_mailboxes = nil
      end

      if attributes.key?(:'has_send_units')
        self.has_send_units = attributes[:'has_send_units']
      else
        self.has_send_units = nil
      end

      if attributes.key?(:'has_ai_units')
        self.has_ai_units = attributes[:'has_ai_units']
      else
        self.has_ai_units = nil
      end

      if attributes.key?(:'has_e2e_encryption')
        self.has_e2e_encryption = attributes[:'has_e2e_encryption']
      else
        self.has_e2e_encryption = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      if @display_name.nil?
        invalid_properties.push('invalid value for "display_name", display_name cannot be nil.')
      end

      if @description.nil?
        invalid_properties.push('invalid value for "description", description cannot be nil.')
      end

      if @price_naira_per_seat.nil?
        invalid_properties.push('invalid value for "price_naira_per_seat", price_naira_per_seat cannot be nil.')
      end

      if @rate_cap_per_min.nil?
        invalid_properties.push('invalid value for "rate_cap_per_min", rate_cap_per_min cannot be nil.')
      end

      if @monthly_included_sends.nil?
        invalid_properties.push('invalid value for "monthly_included_sends", monthly_included_sends cannot be nil.')
      end

      if @has_shared_mailboxes.nil?
        invalid_properties.push('invalid value for "has_shared_mailboxes", has_shared_mailboxes cannot be nil.')
      end

      if @has_send_units.nil?
        invalid_properties.push('invalid value for "has_send_units", has_send_units cannot be nil.')
      end

      if @has_ai_units.nil?
        invalid_properties.push('invalid value for "has_ai_units", has_ai_units cannot be nil.')
      end

      if @has_e2e_encryption.nil?
        invalid_properties.push('invalid value for "has_e2e_encryption", has_e2e_encryption cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @name.nil?
      return false if @display_name.nil?
      return false if @description.nil?
      return false if @price_naira_per_seat.nil?
      return false if @rate_cap_per_min.nil?
      return false if @monthly_included_sends.nil?
      return false if @has_shared_mailboxes.nil?
      return false if @has_send_units.nil?
      return false if @has_ai_units.nil?
      return false if @has_e2e_encryption.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] name Value to be assigned
    def name=(name)
      if name.nil?
        fail ArgumentError, 'name cannot be nil'
      end

      @name = name
    end

    # Custom attribute writer method with validation
    # @param [Object] display_name Value to be assigned
    def display_name=(display_name)
      if display_name.nil?
        fail ArgumentError, 'display_name cannot be nil'
      end

      @display_name = display_name
    end

    # Custom attribute writer method with validation
    # @param [Object] description Value to be assigned
    def description=(description)
      if description.nil?
        fail ArgumentError, 'description cannot be nil'
      end

      @description = description
    end

    # Custom attribute writer method with validation
    # @param [Object] price_naira_per_seat Value to be assigned
    def price_naira_per_seat=(price_naira_per_seat)
      if price_naira_per_seat.nil?
        fail ArgumentError, 'price_naira_per_seat cannot be nil'
      end

      @price_naira_per_seat = price_naira_per_seat
    end

    # Custom attribute writer method with validation
    # @param [Object] rate_cap_per_min Value to be assigned
    def rate_cap_per_min=(rate_cap_per_min)
      if rate_cap_per_min.nil?
        fail ArgumentError, 'rate_cap_per_min cannot be nil'
      end

      @rate_cap_per_min = rate_cap_per_min
    end

    # Custom attribute writer method with validation
    # @param [Object] monthly_included_sends Value to be assigned
    def monthly_included_sends=(monthly_included_sends)
      if monthly_included_sends.nil?
        fail ArgumentError, 'monthly_included_sends cannot be nil'
      end

      @monthly_included_sends = monthly_included_sends
    end

    # Custom attribute writer method with validation
    # @param [Object] has_shared_mailboxes Value to be assigned
    def has_shared_mailboxes=(has_shared_mailboxes)
      if has_shared_mailboxes.nil?
        fail ArgumentError, 'has_shared_mailboxes cannot be nil'
      end

      @has_shared_mailboxes = has_shared_mailboxes
    end

    # Custom attribute writer method with validation
    # @param [Object] has_send_units Value to be assigned
    def has_send_units=(has_send_units)
      if has_send_units.nil?
        fail ArgumentError, 'has_send_units cannot be nil'
      end

      @has_send_units = has_send_units
    end

    # Custom attribute writer method with validation
    # @param [Object] has_ai_units Value to be assigned
    def has_ai_units=(has_ai_units)
      if has_ai_units.nil?
        fail ArgumentError, 'has_ai_units cannot be nil'
      end

      @has_ai_units = has_ai_units
    end

    # Custom attribute writer method with validation
    # @param [Object] has_e2e_encryption Value to be assigned
    def has_e2e_encryption=(has_e2e_encryption)
      if has_e2e_encryption.nil?
        fail ArgumentError, 'has_e2e_encryption cannot be nil'
      end

      @has_e2e_encryption = has_e2e_encryption
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          name == o.name &&
          display_name == o.display_name &&
          description == o.description &&
          price_naira_per_seat == o.price_naira_per_seat &&
          rate_cap_per_min == o.rate_cap_per_min &&
          monthly_included_sends == o.monthly_included_sends &&
          has_shared_mailboxes == o.has_shared_mailboxes &&
          has_send_units == o.has_send_units &&
          has_ai_units == o.has_ai_units &&
          has_e2e_encryption == o.has_e2e_encryption
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [name, display_name, description, price_naira_per_seat, rate_cap_per_min, monthly_included_sends, has_shared_mailboxes, has_send_units, has_ai_units, has_e2e_encryption].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
