=begin
#lockally control plane

#The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 

The version of the OpenAPI document: 0.1.0
Contact: support@lockally.com
Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Lockally::AiApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AiApi' do
  before do
    # run before each test
    @api_instance = Lockally::AiApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AiApi' do
    it 'should create an instance of AiApi' do
      expect(@api_instance).to be_instance_of(Lockally::AiApi)
    end
  end

  # unit tests for v1_ai_config_get
  # Read the tenant&#39;s AI configuration
  # Mode (off/byok/units), model, masked key hint, AI-unit balance, whether the units tier is available on this deployment.
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'v1_ai_config_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_ai_config_put
  # Configure the AI tier
  # Body: {\&quot;mode\&quot;: \&quot;off|byok|units\&quot;, \&quot;model\&quot;: \&quot;...\&quot;, \&quot;anthropic_key\&quot;: \&quot;sk-ant-...\&quot;}. BYOK keys are stored AES-256-GCM encrypted; the cleartext is never returned. Omit anthropic_key to keep the stored one.
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'v1_ai_config_put test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_billing_ai_units_checkout_post
  # Buy prepaid AI units
  # Body: {\&quot;bundle\&quot;: \&quot;100|500|2000\&quot;}. One classification &#x3D; one unit; bundles expire after 6 months. Admin session required. 503 until Paystack billing is configured.
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'v1_billing_ai_units_checkout_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_threads_thread_id_classify_post
  # LLM-classify a thread
  # Returns {intent, urgency, summary, suggested_action} via the tenant&#39;s AI tier (BYOK or prepaid units — see /v1/ai-config). Cached per thread state: unchanged threads return the cache free; ?refresh&#x3D;true forces a re-run. A failed model call charges nothing. 402 when the AI tier is off.
  # @param thread_id 
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :refresh 
  # @return [Object]
  describe 'v1_threads_thread_id_classify_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
