=begin
#lockally control plane

#The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`, or `lk_test_<...>` for a test key. Create keys in the dashboard, or with `POST /v1/api-keys` using a key that holds `tenant:admin`.  The key's plan is checked on every request, so a key stops working if the account moves to a plan without API access, and works again if it moves back.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 

The version of the OpenAPI document: 0.1.0
Contact: support@lockally.com
Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Lockally::AliasesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AliasesApi' do
  before do
    # run before each test
    @api_instance = Lockally::AliasesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AliasesApi' do
    it 'should create an instance of AliasesApi' do
      expect(@api_instance).to be_instance_of(Lockally::AliasesApi)
    end
  end

  # unit tests for v1_aliases_address_delete
  # Delete an alias
  # Hard-delete (no soft-delete window — aliases are cheap to recreate).
  # @param address 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v1_aliases_address_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_aliases_get
  # List aliases
  # @param [Hash] opts the optional parameters
  # @return [V1AliasesGet200Response]
  describe 'v1_aliases_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_aliases_post
  # Create an alias
  # Creates an email alias. &#x60;alias_address&#x60; must be on a verified tenant-owned domain and must not be the address of an existing mailbox (live, suspended or deleted). &#x60;alias_target&#x60; must be an active mailbox in the same workspace; forwarding to an address Lockally does not host is not supported. The alias delivers as soon as the call returns. 
  # @param v1_aliases_post_request 
  # @param [Hash] opts the optional parameters
  # @return [ModelAlias]
  describe 'v1_aliases_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
