=begin
#lockally control plane

#The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 

The version of the OpenAPI document: 0.1.0
Contact: support@lockally.com
Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Lockally::CalendarsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CalendarsApi' do
  before do
    # run before each test
    @api_instance = Lockally::CalendarsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CalendarsApi' do
    it 'should create an instance of CalendarsApi' do
      expect(@api_instance).to be_instance_of(Lockally::CalendarsApi)
    end
  end

  # unit tests for add_calendar_member
  # Add a member to a calendar
  # @param id 
  # @param add_calendar_member_request 
  # @param [Hash] opts the optional parameters
  # @return [CalendarMember]
  describe 'add_calendar_member test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_calendar
  # Create a calendar
  # @param create_calendar_request 
  # @param [Hash] opts the optional parameters
  # @return [Calendar]
  describe 'create_calendar test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_calendar_event
  # Create an event in a calendar
  # @param id 
  # @param create_calendar_event_request 
  # @param [Hash] opts the optional parameters
  # @return [CalendarEvent]
  describe 'create_calendar_event test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_calendar_integration
  # Create a calendar integration
  # @param create_calendar_integration_request 
  # @param [Hash] opts the optional parameters
  # @return [CalendarIntegration]
  describe 'create_calendar_integration test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_calendar
  # Delete a calendar
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_calendar test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_calendar_event
  # Delete a calendar event
  # @param id 
  # @param event_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_calendar_event test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_calendar_integration
  # Delete a calendar integration
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_calendar_integration test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_calendar
  # Get a calendar
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [Calendar]
  describe 'get_calendar test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_calendar_policies
  # Get calendar policies
  # @param [Hash] opts the optional parameters
  # @return [CalendarPolicies]
  describe 'get_calendar_policies test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_calendar_security
  # Get calendar security overview
  # @param [Hash] opts the optional parameters
  # @return [GetCalendarSecurity200Response]
  describe 'get_calendar_security test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_calendar_events
  # List events in a calendar
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [Time] :from 
  # @option opts [Time] :to 
  # @return [ListCalendarEvents200Response]
  describe 'list_calendar_events test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_calendar_integrations
  # List calendar integrations
  # @param [Hash] opts the optional parameters
  # @return [ListCalendarIntegrations200Response]
  describe 'list_calendar_integrations test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_calendar_members
  # List calendar members
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [ListCalendarMembers200Response]
  describe 'list_calendar_members test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_calendars
  # List calendars
  # @param [Hash] opts the optional parameters
  # @return [ListCalendars200Response]
  describe 'list_calendars test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for remove_calendar_member
  # Remove a member from a calendar
  # @param id 
  # @param member_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'remove_calendar_member test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for sync_calendar_integration
  # Trigger sync for a calendar integration
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [CalendarIntegration]
  describe 'sync_calendar_integration test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_calendar
  # Update a calendar
  # @param id 
  # @param update_calendar_request 
  # @param [Hash] opts the optional parameters
  # @return [Calendar]
  describe 'update_calendar test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_calendar_event
  # Update a calendar event
  # @param id 
  # @param event_id 
  # @param update_calendar_event_request 
  # @param [Hash] opts the optional parameters
  # @return [CalendarEvent]
  describe 'update_calendar_event test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_calendar_integration
  # Update a calendar integration
  # @param id 
  # @param update_calendar_integration_request 
  # @param [Hash] opts the optional parameters
  # @return [CalendarIntegration]
  describe 'update_calendar_integration test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_calendar_member
  # Update a calendar member&#39;s role
  # @param id 
  # @param member_id 
  # @param update_calendar_member_request 
  # @param [Hash] opts the optional parameters
  # @return [CalendarMember]
  describe 'update_calendar_member test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_calendar_policies
  # Update calendar policies
  # @param update_calendar_policies_request 
  # @param [Hash] opts the optional parameters
  # @return [CalendarPolicies]
  describe 'update_calendar_policies test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
