=begin
#lockally control plane

#The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 

The version of the OpenAPI document: 0.1.0
Contact: support@lockally.com
Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Lockally::DashboardApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DashboardApi' do
  before do
    # run before each test
    @api_instance = Lockally::DashboardApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DashboardApi' do
    it 'should create an instance of DashboardApi' do
      expect(@api_instance).to be_instance_of(Lockally::DashboardApi)
    end
  end

  # unit tests for get_audit_summary
  # Audit summary for the dashboard
  # @param [Hash] opts the optional parameters
  # @return [GetAuditSummary200Response]
  describe 'get_audit_summary test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_domains_status
  # Domain health status for the dashboard
  # @param [Hash] opts the optional parameters
  # @return [GetDomainsStatus200Response]
  describe 'get_domains_status test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_integrations_summary
  # Integrations summary for the dashboard
  # @param [Hash] opts the optional parameters
  # @return [GetIntegrationsSummary200Response]
  describe 'get_integrations_summary test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_security
  # Security overview for the dashboard
  # @param [Hash] opts the optional parameters
  # @return [GetSecurity200Response]
  describe 'get_security test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_storage
  # Storage usage for the dashboard
  # @param [Hash] opts the optional parameters
  # @return [GetStorage200Response]
  describe 'get_storage test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_tenant_health
  # Full tenant health report
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'get_tenant_health test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_user_insights
  # User insights for the dashboard
  # @param [Hash] opts the optional parameters
  # @return [GetUserInsights200Response]
  describe 'get_user_insights test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
