=begin
#lockally control plane

#The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 

The version of the OpenAPI document: 0.1.0
Contact: support@lockally.com
Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Lockally::DirectoryApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DirectoryApi' do
  before do
    # run before each test
    @api_instance = Lockally::DirectoryApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DirectoryApi' do
    it 'should create an instance of DirectoryApi' do
      expect(@api_instance).to be_instance_of(Lockally::DirectoryApi)
    end
  end

  # unit tests for get_directory_activity
  # Get recent directory activity
  # @param [Hash] opts the optional parameters
  # @return [GetDirectoryActivity200Response]
  describe 'get_directory_activity test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_directory_permissions
  # Get directory permission settings
  # @param [Hash] opts the optional parameters
  # @return [DirectoryPermissions]
  describe 'get_directory_permissions test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_directory_stats
  # Get directory statistics
  # @param [Hash] opts the optional parameters
  # @return [GetDirectoryStats200Response]
  describe 'get_directory_stats test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_gal_settings
  # Get Global Address List settings
  # @param [Hash] opts the optional parameters
  # @return [GALSettings]
  describe 'get_gal_settings test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for rebuild_gal_index
  # Rebuild the GAL search index
  # @param [Hash] opts the optional parameters
  # @return [GALSettings]
  describe 'rebuild_gal_index test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for sync_gal
  # Sync GAL with external directory sources
  # @param [Hash] opts the optional parameters
  # @return [GALSettings]
  describe 'sync_gal test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_directory_permissions
  # Update directory permission settings
  # @param update_directory_permissions_request 
  # @param [Hash] opts the optional parameters
  # @return [DirectoryPermissions]
  describe 'update_directory_permissions test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_gal_settings
  # Update GAL settings
  # @param update_gal_settings_request 
  # @param [Hash] opts the optional parameters
  # @return [GALSettings]
  describe 'update_gal_settings test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
