=begin
#lockally control plane

#The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 

The version of the OpenAPI document: 0.1.0
Contact: support@lockally.com
Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Lockally::DistributionListsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DistributionListsApi' do
  before do
    # run before each test
    @api_instance = Lockally::DistributionListsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DistributionListsApi' do
    it 'should create an instance of DistributionListsApi' do
      expect(@api_instance).to be_instance_of(Lockally::DistributionListsApi)
    end
  end

  # unit tests for create_distribution_list
  # Create a distribution list
  # @param create_distribution_list_request 
  # @param [Hash] opts the optional parameters
  # @return [DistributionListDetail]
  describe 'create_distribution_list test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_distribution_list
  # Delete a distribution list
  # @param address Distribution list email address
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_distribution_list test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_distribution_list
  # Get a distribution list
  # @param address Distribution list email address
  # @param [Hash] opts the optional parameters
  # @return [DistributionListDetail]
  describe 'get_distribution_list test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_distribution_lists
  # List distribution lists
  # @param [Hash] opts the optional parameters
  # @return [ListDistributionLists200Response]
  describe 'list_distribution_lists test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for replace_distribution_list_members
  # Replace distribution list members
  # @param address Distribution list email address
  # @param replace_distribution_list_members_request 
  # @param [Hash] opts the optional parameters
  # @return [ReplaceDistributionListMembers200Response]
  describe 'replace_distribution_list_members test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
