=begin
#lockally control plane

#The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 

The version of the OpenAPI document: 0.1.0
Contact: support@lockally.com
Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Lockally::DraftsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DraftsApi' do
  before do
    # run before each test
    @api_instance = Lockally::DraftsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DraftsApi' do
    it 'should create an instance of DraftsApi' do
      expect(@api_instance).to be_instance_of(Lockally::DraftsApi)
    end
  end

  # unit tests for v1_drafts_draft_id_approve_post
  # Approve a pending draft (human)
  # Sends the draft exactly as reviewed, through the agent stream (loop detector included). Fires draft.approved.
  # @param draft_id 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'v1_drafts_draft_id_approve_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_drafts_draft_id_cancel_post
  # Withdraw a pending draft
  # Only the API key that created the draft may cancel it.
  # @param draft_id 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'v1_drafts_draft_id_cancel_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_drafts_draft_id_get
  # Get a draft
  # @param draft_id 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'v1_drafts_draft_id_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_drafts_draft_id_reject_post
  # Reject a pending draft (human)
  # Body: {\&quot;reason\&quot;: \&quot;...\&quot;} (optional). Fires draft.rejected.
  # @param draft_id 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'v1_drafts_draft_id_reject_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_drafts_get
  # List drafts
  # Filter with ?status&#x3D;pending_approval|sent|rejected|cancelled. Keys see drafts of granted mailboxes; admin sessions see all.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :status 
  # @option opts [Integer] :limit 
  # @return [Object]
  describe 'v1_drafts_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_inboxes_mailbox_drafts_post
  # Propose a new conversation as a draft
  # New-conversation drafts ALWAYS require human approval (policy flag new_thread). Idempotency-Key required.
  # @param mailbox 
  # @param idempotency_key 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'v1_inboxes_mailbox_drafts_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_threads_thread_id_drafts_post
  # Propose a reply as a draft
  # The safe default over /reply: the deterministic policy engine auto-sends clean in-thread replies and holds anything risky (PII, new recipients, injection-flagged threads, always-approve mailboxes) for human approval. Fires draft.pending_approval when held. Idempotency-Key required.
  # @param thread_id 
  # @param idempotency_key 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'v1_threads_thread_id_drafts_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
