=begin
#lockally control plane

#The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 

The version of the OpenAPI document: 0.1.0
Contact: support@lockally.com
Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Lockally::EncryptionApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'EncryptionApi' do
  before do
    # run before each test
    @api_instance = Lockally::EncryptionApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of EncryptionApi' do
    it 'should create an instance of EncryptionApi' do
      expect(@api_instance).to be_instance_of(Lockally::EncryptionApi)
    end
  end

  # unit tests for batch_lookup_public_keys
  # Batch-lookup public keys by email
  # @param emails Comma-separated list of email addresses
  # @param [Hash] opts the optional parameters
  # @return [BatchLookupPublicKeys200Response]
  describe 'batch_lookup_public_keys test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_encryption_key
  # Upload an encryption key pair
  # @param create_encryption_key_request 
  # @param [Hash] opts the optional parameters
  # @return [CreateEncryptionKey201Response]
  describe 'create_encryption_key test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_encryption_recovery
  # Store an encryption recovery blob
  # @param create_encryption_recovery_request 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'create_encryption_recovery test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_encryption_key
  # Get encryption key for a mailbox
  # @param email 
  # @param [Hash] opts the optional parameters
  # @return [GetEncryptionKey200Response]
  describe 'get_encryption_key test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for rotate_encryption_key
  # Rotate an encryption key
  # @param rotate_encryption_key_request 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'rotate_encryption_key test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
