=begin
#lockally control plane

#The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 

The version of the OpenAPI document: 0.1.0
Contact: support@lockally.com
Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Lockally::MigrationsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'MigrationsApi' do
  before do
    # run before each test
    @api_instance = Lockally::MigrationsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MigrationsApi' do
    it 'should create an instance of MigrationsApi' do
      expect(@api_instance).to be_instance_of(Lockally::MigrationsApi)
    end
  end

  # unit tests for cancel_migration
  # Cancel a running migration
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [DiscoverMigration202Response]
  describe 'cancel_migration test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for check_migration_dns
  # Check DNS readiness for cutover
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'check_migration_dns test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_migration
  # Create a migration
  # @param create_migration_request 
  # @param [Hash] opts the optional parameters
  # @return [Migration]
  describe 'create_migration test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_migration_credential
  # Store a migration credential
  # @param create_migration_credential_request 
  # @param [Hash] opts the optional parameters
  # @return [MigrationCredential]
  describe 'create_migration_credential test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_migration
  # Delete a migration
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_migration test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_migration_credential
  # Delete a migration credential
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_migration_credential test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delta_sync_migration
  # Run a delta sync
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [StartMigration202Response]
  describe 'delta_sync_migration test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for discover_migration
  # Discover source mailboxes
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [DiscoverMigration202Response]
  describe 'discover_migration test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for final_sync_migration
  # Run the final sync before cutover
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [StartMigration202Response]
  describe 'final_sync_migration test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_migration
  # Get a migration
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [Migration]
  describe 'get_migration test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_migration_progress
  # Get migration progress
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [MigrationProgress]
  describe 'get_migration_progress test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_migration_credentials
  # List migration credentials
  # @param [Hash] opts the optional parameters
  # @return [ListMigrationCredentials200Response]
  describe 'list_migration_credentials test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_migration_events
  # List migration events
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [ListMigrationEvents200Response]
  describe 'list_migration_events test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_migration_mailboxes
  # List migration mailboxes
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [ListMigrationMailboxes200Response]
  describe 'list_migration_mailboxes test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_migrations
  # List migrations
  # @param [Hash] opts the optional parameters
  # @return [ListMigrations200Response]
  describe 'list_migrations test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for map_migration
  # Map source to destination mailboxes
  # @param id 
  # @param map_migration_request 
  # @param [Hash] opts the optional parameters
  # @return [DiscoverMigration202Response]
  describe 'map_migration test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for retry_migration
  # Retry a failed or cancelled migration
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [DiscoverMigration202Response]
  describe 'retry_migration test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for start_migration
  # Start the migration
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [StartMigration202Response]
  describe 'start_migration test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_migration
  # Update a migration
  # @param id 
  # @param update_migration_request 
  # @param [Hash] opts the optional parameters
  # @return [Migration]
  describe 'update_migration test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_migration_mailbox
  # Update a migration mailbox
  # @param id 
  # @param mbx_id 
  # @param update_migration_mailbox_request 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'update_migration_mailbox test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for validate_migration
  # Validate migrated data
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [StartMigration202Response]
  describe 'validate_migration test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
