=begin
#lockally control plane

#The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 

The version of the OpenAPI document: 0.1.0
Contact: support@lockally.com
Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Lockally::SendApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SendApi' do
  before do
    # run before each test
    @api_instance = Lockally::SendApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SendApi' do
    it 'should create an instance of SendApi' do
      expect(@api_instance).to be_instance_of(Lockally::SendApi)
    end
  end

  # unit tests for v1_messages_get
  # List outbound messages
  # Returns recent outbound messages for the calling tenant, sorted newest first. Backs the send-status pill in the SvelteKit /sends view and the outbound search box. 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :status 
  # @option opts [String] :sender Exact match against the &#x60;from&#x60; mailbox.
  # @option opts [String] :q Free-text search across subject + sender.
  # @option opts [Time] :since Only messages queued at or after this RFC 3339 instant.
  # @option opts [String] :cursor queued_at of the prior page boundary. Pass back the &#x60;next_cursor&#x60; returned by the previous call.
  # @option opts [Integer] :limit 
  # @return [V1MessagesGet200Response]
  describe 'v1_messages_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_messages_id_delete
  # Cancel a scheduled send
  # Cancels a still-scheduled message (future queued_at). Already sending/sent → 409.
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v1_messages_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_messages_id_get
  # Get message status
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [MessageDetail]
  describe 'v1_messages_id_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_messages_stats_get
  # Aggregate delivery stats
  # Counts by delivery outcome (delivered/bounced/deferred/complaint) plus rates over a window, from the delivery-event store. Privacy-first: this reflects what receiving servers reported, NOT whether a human opened the mail — Lockally does no open/click tracking. 
  # @param [Hash] opts the optional parameters
  # @option opts [Time] :from Window start (default 7 days ago).
  # @option opts [Time] :to Window end (default now).
  # @option opts [String] :domain Filter by sender domain.
  # @return [MessageStats]
  describe 'v1_messages_stats_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_send_batch_post
  # Send a batch of emails
  # Sends up to 500 messages in one call. Each is validated and enqueued independently — a bad message fails only its own slot (partial success, HTTP 200). One &#x60;Idempotency-Key&#x60; header covers the batch; per-message keys are derived as &#x60;&lt;key&gt;:&lt;index&gt;&#x60;. 
  # @param idempotency_key 
  # @param v1_send_batch_post_request 
  # @param [Hash] opts the optional parameters
  # @return [V1SendBatchPost200Response]
  describe 'v1_send_batch_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_send_post
  # Send an email
  # Submits an email for delivery via lockally. Returns 202 immediately once the message is accepted into lockally&#39;s queue; the actual SMTP submission to the recipient is async. Track delivery via &#x60;GET /v1/messages/{id}&#x60; or webhook subscriptions for &#x60;delivery.delivered&#x60; / &#x60;delivery.bounced&#x60; / &#x60;delivery.complaint&#x60;.  **Idempotency-Key required.** Per design L7 — any unique string per send, 24-hour dedupe window. Repeated calls with the same key return byte-exact the original response and do NOT create a duplicate message.  **Sender authorisation.** &#x60;from&#x60; must be a non-disabled mailbox owned by the calling tenant on a verified domain. Sending from aliases is not yet supported.  **Rate cap.** Per-tenant &#x60;rate_cap_per_min&#x60; (returned on &#x60;/v1/tenant&#x60;) is enforced — 429 with &#x60;Retry-After: 60&#x60; once tripped.  **Recipient warning.** Over 25 total recipients (To+Cc+Bcc) sets a &#x60;warning&#x60; field in the response — large fan-outs queue noticeably at scale. Hard cap is 100/send. 
  # @param idempotency_key 
  # @param v1_send_post_request 
  # @param [Hash] opts the optional parameters
  # @return [V1SendPost202Response]
  describe 'v1_send_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
